### ISSUE TITLE
Sass file watching via JavaScript API

### ISSUE THREAD

**Issue by paulshryock** [sass/embedded-host-node#119]
Is there a way to compile sass and watch for changes programmatically?

I would expect to be able to pass a `watch` option similar to passing `--watch` to the CLI.

```javascript
import sass from 'sass-embedded'

await sass.compileAsync('src/main.scss', { watch: true })
	.then((result) => {
		console.log(result.css)
	})
```

I haven't found anything like that so far, but would love to know if there's a way to avoid having to roll my own via chokidar.

**Comment by jathak** [comment]
This isn't something that makes sense for us to add to Sass specifically, since you could just use a package like `chokidar` directly.

**Comment by paulshryock** [comment]
Fair enough, thanks. I gave it a shot with Chokidar and that ended up being pretty straightforward.
