### ISSUE TITLE
Synchronous compilation API

### ISSUE THREAD

**Issue by Awjin** [sass/embedded-host-node#12]
The Sass JS API has both asynchronous and synchronous methods for compiling Sass: `render()` and `renderSync()`. To implement `renderSync()`—and eventually, a new synchronous API—we need a way to transform event-driven compilation into a synchronous call. This is because at its core, the host invokes the Embedded Dart Sass compiler as a Node child process which communicates via an event-driven API.

## Background

This is how we’d use Node worker threads to hide asynchronous compilation:

- When the synchronous API is called, the main thread spawns a worker thread, passing it Sass to compile asynchronously.
- The main thread goes to sleep via `Atomics.wait()`, waiting on a shared mutex.
- After finishing the compilation, the worker thread wakes the main thread by signaling the shared mutex, and then passes the result to the main thread.

The trouble is, threads can only pass serializable data to each other; threads cannot pass instances of classes or functions. Since `renderSync()` accepts importers and functions to invoke during compilation, we need a way to access them from the worker thread.

## Design Idea

Keep importers and functions in the main thread, and let the worker thread invoke them.

First the worker thread:

- Serializes the import/function call request.
- Passes the request to the main thread, then promisifies the main thread’s response and waits.
- Notifies and wakes up the main thread.

Main thread:

- Deserializes the request and invokes the appropriate importer/function.
- Serializes the response and passes it to the worker thread.
- Sleeps.

Worker thread:

- Deserializes response and finishes compilation.
- Passes the result to the main thread, then notifies and wakes up the main thread.

Main thread:
- Returns the compilation result, seemingly synchronously.

### Stringify functions
Serialize importer methods and functions to strings, then pass them to the worker thread, which then invokes them with `eval()`.

This causes the functions to lose any context/closures.

### No synchronous API?

Only expose `render()`.

The original purpose of the sync call was to speed up compilation. For the Embedded Sass compiler, a sync call is irrelevant since its speed comes from the natively compiled executable core. The code needed for the sync conversion is complex and creates a pattern that goes against the async design philosophy of Node.

If someone implements an embedded host in a language that’s not async by design, the `render()` call would just be synchronous.

Not supporting `renderSync()`, though, is a breaking change. If users are currently using sync calls and want to upgrade to Embedded Sass, they will have to refactor their codebase to be async. I think this is low risk, since Node users most likely have their code structured as async, but it’s impossible to know for sure.

**Comment by nex3** [comment]
I think your plan is sound. Fortunately the embedded protocol gives you a built-in serialization format for serializing most of the information you want to pass back and forth between the worker and the main thread.

Let's put this on the back burner for now, and focus on getting the async `render()` implemented and out for beta testing. I think you're right that asking users to use that for now is low-risk. We probably want `renderSync()` in place for a stable release, but I don't think we need it for early use.
