### ISSUE TITLE
Feature request: Custom functions instead of `fs` module

### ISSUE THREAD

**Issue by glenn2223** [sass/embedded-host-node#122]
I can see that you use node's `fs` modules - like [lib/src/compiler-path.ts](https://github.com/sass/embedded-host-node/blob/921b83e449f422abb94a280aedc38bd09365f7d7/lib/src/compiler-path.ts) (and others). However I was wondering if we could have a new option that allows custom functions instead - like for web extensions for the [vscode.dev](vscode.dev) site

I know this goes against the `-node` in `embedded-host-node` but with such a smaller codebase I thought this would be the place to ask 

----

Copy from https://code.visualstudio.com/api/extension-guides/web-extensions#migrate-extension-with-code

To make sure as much source code as possible can be reused, here are a few techniques:
- To polyfill a Node.js core module such as path, add an entry to [resolve.fallback](https://webpack.js.org/configuration/resolve/#resolvefallback).
- To provide a Node.js global such as process use the [DefinePlugin plugin](https://webpack.js.org/plugins/define-plugin).
- Use node modules that work in both browser and node runtime. Node modules can do that by defining both browser and main entry points. Webpack will automatically use the one matching its target. Examples of node modules that do this are [request-light](https://github.com/microsoft/node-request-light) and [vscode-nls](https://github.com/Microsoft/vscode-nls).
- To provide an alternate implementation for a node module or source file, use [resolve.alias](https://webpack.js.org/configuration/resolve/#resolvealias).
- Separate your code in a browser part, Node.js part, and common part. In common, only use code that works in both the browser and Node.js runtime. Create abstractions for functionality that has different implementations in Node.js and the browser.
- Look out for usages of path, URI.file, context.extensionPath, rootPath. uri.fsPath. These will not work with virtual workspaces (non-file system) as they are used in VS Code for the Web. Instead use URIs with URI.parse, context.extensionUri. The [vscode-uri](https://www.npmjs.com/package/vscode-uri) node module provides joinPath, dirName, baseName, extName, resolvePath.
- **Look out for usages of fs. Replace by using vscode workspace.fs.** _<= the key one_

**Comment by jathak** [comment]
For the embedded host, we need the Node APIs not just for accessing the filesystem, but also for running the embedded compiler process (which wouldn't work in the browser). See https://github.com/sass/dart-sass/issues/25 for an issue tracking browser support for the compiled-to-JS version.
