### ISSUE TITLE
Implement asynchronous API `render()`

### ISSUE THREAD

**Issue by Awjin** [sass/embedded-host-node#13]
This should replicate the current Sass JS API call. This work can be split up by first releasing a stripped down version of `render` that supports core behavior, then gradually adding more advanced support for custom importers and functions:

- [x] basic compile functionality with sourcemaps
- [x] syntax and style control
- [x] custom functions
- [x] custom importers

**Comment by dickeylth** [comment]
Are we making any progress on `custom importers` support?

**Comment by Awjin** [comment]
This issue is outdated. Importers are now supported.
