### ISSUE TITLE
`charset` option is not supported

### ISSUE THREAD

**Issue by sapphi-red** [sass/embedded-host-node#131]
Because of the following reason, `charset` option is not supported.

- embedded host implements legacy-API importers as a wrapper around the modern API
- modern API does not support `charset` option (https://github.com/sass/sass/issues/3242)

I think this feature can also be realized by other ways like simply replacing `@charset "\w+"`.
But since this is an incompatibility, I created this issue.

**Comment by nex3** [comment]
Blocked on https://github.com/sass/sass/issues/3242

**Comment by ntkme** [comment]
Should be available now with 1.54.2 release.
