### ISSUE TITLE
Add a way for offline installation

### ISSUE THREAD

**Issue by tychenjiajun** [sass/embedded-host-node#132]
It seems that `yarn install sass-embedded` will download [embedded-protocol](https://github.com/sass/embedded-protocol) and [dart-sass-embedded](https://github.com/sass/dart-sass-embedded) from Github, which makes it impossible to succeed in a network that has no Github access?

**Comment by nex3** [comment]
We download these files on installation because we don't know until installation-time which specific operating system x architecture combination you'll need. I don't think it's feasible for us to bundle all of the embedded executables with the npm package, so how else could we make them available?

**Comment by tychenjiajun** [comment]
In node-sass, we have [binary configuration parameters](https://github.com/sass/node-sass#binary-configuration-parameters). Can we have a similar config in this project?

**Comment by nex3** [comment]
Specifying a proxy server isn't really "offline" so much as "online from a different place". I think #117 is what you want, which will make Dart Sass follow npm's conventions for locating proxy servers.
