### ISSUE TITLE
Windows - Embedded Dart Sass couldn't find the embedded compiler executable

### ISSUE THREAD

**Issue by stevefulghum** [sass/embedded-host-node#139]
We recently updated our Sass dependency to use sass-embedded. So far we haven't run into issues when compiling with MacOS and Ubuntu machines. Teammates on Windows have reported the following error: 
`Embedded Dart Sass couldn't find the embedded compiler executable`

Here's an example of the error output: 
```
[webpack] [webpack-cli] Failed to load 'C:\dev\<project>\webpack.config.ts' config
[webpack] [webpack-cli] Error: Embedded Dart Sass couldn't find the embedded compiler executable.
[webpack]     at C:\dev\<project>\node_modules\sass-embedded\lib\src\compiler-path.ts:22:9
[webpack]     at Object.<anonymous> (C:\dev\<project>\node_modules\sass-embedded\lib\src\compiler-path.ts:25:3)
[webpack]     at Module._compile (C:\dev\<project>\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
[webpack]     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[webpack]     at Object.require.extensions.<computed> [as .js] (C:\dev\<project>\node_modules\ts-node\src\index.ts:1300:43)
[webpack]     at Module.load (internal/modules/cjs/loader.js:928:32)
[webpack]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[webpack]     at Module.require (internal/modules/cjs/loader.js:952:19)
[webpack]     at require (C:\dev\<project>\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
[webpack]     at Object.<anonymous> (C:\dev\<project>\node_modules\sass-embedded\lib\src\async-compiler.ts:9:1)
```

**Comment by jathak** [comment]
Can you provide a standalone reproduction of this issue? It's possible this is an issue with how Webpack is configured.

**Comment by ntkme** [comment]
We need more details but here are two possible reasons:

1. `npm postinstall` did not run, e.g. `npm install --ignore-scripts`.
2. `npm postinstall` did run, but did not download the binary: e.g. according to the line below, if the user has `.dev` in npm's working directory, `dart-sass-embedded` is not downloaded:
    https://github.com/sass/embedded-host-node/blob/b2908abb5b1ccebe4b1e5dd457c0dbdbb7a1de35/download-compiler-for-end-user.js#L7
