### ISSUE TITLE
1.51

### ISSUE THREAD

**Issue by OlegKipchatov** [sass/embedded-host-node#141]
DartSass version 1.51 was released over two weeks ago, but this package has not been updated
Is this package live?
https://github.com/sass/dart-sass/releases/tag/1.51.0

**Comment by ntkme** [comment]
The CI for this release glitched and failed: https://github.com/sass/embedded-host-node/actions/runs/2224099196

Maybe @nex3 or @jathak can help trigger a rerun?

**Comment by jathak** [comment]
It should be released now.
