### ISSUE TITLE
32-bit `arm` architecture support

### ISSUE THREAD

**Issue by ajmeese7** [sass/embedded-host-node#142]
When `sass-loader` (which has this package as a dependency) tries to install, I get the error message `Error: Architecure arm is not supported.`

It would be great if support for this architecture could be added, I would love to use this on the web server I am hosting on my Raspberry Pi!

**Comment by jathak** [comment]
We should be able to release 32-bit ARM binaries once Dart 2.18 is released, which includes a fix for an issue that was blocking this previously.

**Comment by ajmeese7** [comment]
That would be awesome, thanks!

**Comment by kdagnan** [comment]
For the record - I was able to get this working on Apple silicon - not entirely sure if this is due to Rosetta or not.

**Comment by nex3** [comment]
Apple Silicon is 64-bit; this issue is tracking 32-bit ARM support.

**Comment by nex3** [comment]
Fixed by https://github.com/sass/embedded-host-node/pull/161
