### ISSUE TITLE
Sass-embedded doesn't support Linux distributions that use musl-libc.

### ISSUE THREAD

**Issue by Arsnj** [sass/embedded-host-node#155]
#13 118.2 npm ERR! path /app/node_modules/sass-embedded
#13 118.2 npm ERR! command failed
#13 118.2 npm ERR! command sh -c node ./download-compiler-for-end-user.js
#13 118.2 npm ERR! Error: sass-embedded doesn't support Linux distributions that use musl-libc.
#13 118.2 npm ERR!     at checkForMusl (/app/node_modules/sass-embedded/dist/tool/utils.js:132:11)
#13 118.2 npm ERR!     at async getDartSassEmbedded (/app/node_modules/sass-embedded/dist/tool/utils.js:97:5)
#13 118.2 npm ERR!     at async /app/node_modules/sass-embedded/download-compiler-for-end-user.js:13:5

**Comment by Goodwine** [comment]
The issue is that Dart doesn't support musl-libc, only glibc. Because Sass is built with Dart we can't provide an embedded version that would work with a Linux distro that uses musl-libc.

See https://github.com/dart-lang/sdk/issues/40906
