### ISSUE TITLE
Url for sass-embedded assets as an environment variable

### ISSUE THREAD

**Issue by Martisek** [sass/embedded-host-node#156]
If someone has to work in fully isolated system (= no access to npmjs.com as well as github.com), it will be quite advantageous to have url for sass-embedded asset downloading based on an environment variable. Nowadays mentioned url is hardcoded (in utils.js).

Our idea: 
``const baseUrlToAssets = process.env.SASS_EMBEDDED_ASSET_URL; // Easy to overload
``
``
 ...
 assetUrl: `${baseUrlToAssets}` + `${version}`
 ...
``

**Comment by nex3** [comment]
I think this will be redundant when https://github.com/sass/embedded-host-node/issues/145 is implemented.
