### ISSUE TITLE
Can't download via npm behind a proxy

### ISSUE THREAD

**Issue by AncientGrief** [sass/embedded-host-node#159]
See here: https://stackoverflow.com/questions/73320212/npm-econnrefused-with-or-without-proxy-trying-to-install-sass-embedded

Is there a way to manually download it and get it running? The pure JS version is unusable atm, since it takes 4 minutes to compile my sass files.

This problem seems to occur with this package only, since npm tries to download the zip file directly from github.

**Comment by nex3** [comment]
How exactly would we address this? How should we access npm's config if not through environment variables?

**Comment by AncientGrief** [comment]
How about this:

```js
const execSync = require('child_process').execSync;

const proxy = execSync('npm config get proxy',
    { stdio: ['ignore', 'pipe', 'pipe'] }).toString().replace(/\n$/, '');

console.log(proxy);
process.exit(1);
```

Adapted from here: https://stackoverflow.com/a/48172021/3023032

**Comment by ntkme** [comment]
There is no guarantee that `npm` won’t change how the command works in the future, so it is probably better to the underneath library from npm instead of invoke cli.

**Comment by nex3** [comment]
I think this will be irrelevant anyway once https://github.com/sass/embedded-host-node/pull/158 lands, so I'm going to close it out.
