### ISSUE TITLE
The new update does not contains Dart Sass embedded

### ISSUE THREAD

**Issue by JuniorEC** [sass/embedded-host-node#163]
Erro occurs on build project

![image](https://user-images.githubusercontent.com/24255719/187988174-a7fced30-c63d-45d2-972f-2ff026b87306.png)
The folter "sass-embedded-${process.platform}-${process.arch}" is not inside on new version 1.54.8
![image](https://user-images.githubusercontent.com/24255719/187988271-5d2bfed3-8691-452f-9b26-b6db53664dcd.png)

**Comment by ntkme** [comment]
The packaging has changed in latest release, now you need to `npm install sass-embedded-win32-x64` (or a different one) for your current platform.

#164 will fix the confusing error message.

**Comment by nex3** [comment]
My understanding (verified by some manual testing) was that npm would automatically install the correct optional dependency for the current platform. Why isn't that happening here? @alan-agius4 @ahabhgk

**Comment by ntkme** [comment]
@nex3 New installation without `package-lock.json` seems to work, however, if you have an existing installation e.g. `1.54.4` and then run `npm update sass-embedded`, it somehow does not install optional dependency, and this seems to be a bug in `npm`: https://github.com/npm/cli/issues/4828

**Comment by ntkme** [comment]
@JuniorEC Are you using `yarn` instead of `npm`?

**Comment by alan-agius4** [comment]
@nex3 indeed it should. 

@JuniorEC, can you please provide the output of the below?
 
```
node -p "process.arch"
```

**Comment by JuniorEC** [comment]
> @nex3 indeed it should.
> 
> @JuniorEC, can you please provide the output of the below?
> 
> ```
> node -p "process.arch"
> ```

The result is x64

**Comment by alan-agius4** [comment]
@JuniorEC, can you try to remove the lock file and see if the problem persists? Which package manager and version are you using?

**Comment by JuniorEC** [comment]
> @JuniorEC, can you try to remove the lock file and see if the problem persists? Which package manager and version are you using?

I am use npm and the version is latest.

i runned npm install sass-embedded-win32-x64 and this solves the problem, any dependency of my project use this lib.

**Comment by JuniorEC** [comment]
> My understanding (verified by some manual testing) was that npm would automatically install the correct optional dependency for the current platform. Why isn't that happening here? @alan-agius4 @ahabhgk

That's exactly what happened, I was investigating inside node_modules, and I didn't find it there, only after the build command, but without the module initially commented

**Comment by Natuu** [comment]
On my project, updating package.json with
```json
"os": [
    "darwin",
    "linux",
    "win32"
  ],
"cpu": [
    "x64",
    "arm",
    "ia32"
  ]
```
and running 

```bash
rm -rf ./node_modules/
npm cache clear --force
npm i
```

Updated my package-lock.json and did the trick, I can now again run `npm ci` on a different os and arch

**Comment by nex3** [comment]
> > My understanding (verified by some manual testing) was that npm would automatically install the correct optional dependency for the current platform. Why isn't that happening here? @alan-agius4 @ahabhgk
> 
> That's exactly what happened, I was investigating inside node_modules, and I didn't find it there, only after the build command, but without the module initially commented

I'm not sure I understand—you say "that's what happened", but it sounds like you _didn't_ get the optional dependency installed. Which is it?

**Comment by buddhist-uni** [comment]
Hi everyone, I'm using sass-embedded inside a Jekyll project (Ruby) and getting a similar (?) error:

```No such file or directory - /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/sass-embedded-1.58.0/ext/sass/sass_embedded/src/dart````

Reinstalling the gems didn't help... Any ideas? Thank you 😊❤️🙏

**Comment by nex3** [comment]
> Hi everyone, I'm using sass-embedded inside a Jekyll project (Ruby) and getting a similar (?) error:
> 
> ```
> No such file or directory - /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/sass-embedded-1.58.0/ext/sass/sass_embedded/src/dart
> ```
> 
> Reinstalling the gems didn't help... Any ideas? Thank you blushheartpray

This is the repository for the Node.js embedded host, not Ruby.
