### ISSUE TITLE
Deploy npm failed

### ISSUE THREAD

**Issue by David--K** [sass/embedded-host-node#202]
With the 1.58.0 release the last run of the `Deploy npm` job failed: https://github.com/sass/embedded-host-node/actions/runs/4069867897/jobs/7010247909.

The latest available version of sass-embedded on npm is still 1.57.1 (https://www.npmjs.com/package/sass-embedded). 

Is it possible to make 1.58.0 available on npm?

**Comment by nex3** [comment]
https://github.com/sass/embedded-host-node/pull/204 should fix the issue, and we'll be releasing 1.58.1 soon.
