### ISSUE TITLE
package.json should be updated to support TypeScripts bundler module resolution

### ISSUE THREAD

**Issue by DavidZidar** [sass/embedded-host-node#247]
I am trying to use TypeScripts `"moduleResolution": "Bundler"`-feature and I'm blocked by the `sass-embedded`-package.

This is the error that I'm getting from TypeScript:
> buildscript.ts:1:30 - error TS7016: Could not find a declaration file for module 'sass-embedded'. '/projectPath/node_modules/sass-embedded/dist/lib/index.mjs' implicitly has an 'any' type.
>   There are types at '/projectPath/node_modules/sass-embedded/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'sass-embedded' library may need to update its package.json or typings.

From what I can gather it seems that it is no longer enough to specify `"types": "dist/types/index.d.ts"`, the package file should also include the types in exports as well.

**Comment by nex3** [comment]
It looks like somehow we aren't shipping TypeScript types at all, so we should probably fix that too :sweat_smile:.

**Comment by DavidZidar** [comment]
@nex3 Just saw you finally released this update, but this still isn't working unfortunately. The paths do not seem to be correct either?

From your `package.json`:
```
"exports": {
  "import": {
    "types": "./dist/lib/index.m.d.ts",
    "default": "./dist/lib/index.mjs"
  },
  "types": "./dist/lib/index.d.ts",
  "default": "./dist/lib/index.js"
}
```

I can only find types under `./dist/types/`, not `./dist/lib/`, and there is no `.m.d.ts`-file at all.

**Comment by ntkme** [comment]
The latest release did not work: https://github.com/sass/embedded-host-node/actions/runs/6489515014/job/17624098258

**Comment by ntkme** [comment]
@nex3 1.69.3 wasn't released due to the following issue. I think we should reopen this and try again? 

```
Error: cp: no such file or directory: dist/lib/src/vendor/sass/index.d.ts
    at Object.error (/home/runner/work/embedded-host-node/embedded-host-node/node_modules/shelljs/src/common.js:110:27)
    at /home/runner/work/embedded-host-node/embedded-host-node/node_modules/shelljs/src/cp.js:246:14
    at Array.forEach (<anonymous>)
    at Object._cp (/home/runner/work/embedded-host-node/embedded-host-node/node_modules/shelljs/src/cp.js:243:11)
    at Object.cp (/home/runner/work/embedded-host-node/embedded-host-node/node_modules/shelljs/src/common.js:384:25)
    at /home/runner/work/embedded-host-node/embedded-host-node/tool/prepare-release.ts:20:11
```

**Comment by nex3** [comment]
:weary:

**Comment by DavidZidar** [comment]
I think it's working now, thanks @nex3!
