### ISSUE TITLE
SASS-embedded disable source maps

### ISSUE THREAD

**Issue by StfBauer** [sass/embedded-host-node#267]
I use dart-sass via embedded in Hugo. Somehow I fail to disable source maps. Is there any option to do this that I have missed.

**Comment by ntkme** [comment]
Hugo uses https://github.com/bep/godartsass. Please ask in that repo or in huge community. It has nothing to do with this repository.

**Comment by StfBauer** [comment]
Well thanks for point me to that direction but I use the NPM Package "sass-embedded": "^1.69.5".

So this is not the repo for it?

Thanks in advance.

**Comment by ntkme** [comment]
Can you explain how are you using sass in hugo? Hugo does not use the npm package even if you install it...

**Comment by ntkme** [comment]
https://gohugo.io/hugo-pipes/transpile-sass-to-css/

In hugo there are only two options, libsass or dartsass (invoked via [godartsass](https://github.com/bep/godartsass) wrapper. There isn't an option to use npm `sass-embedded`, unless you're doing something out side of hugo.
