### ISSUE TITLE
Making dart-sass binary install global ?

### ISSUE THREAD

**Issue by atiro** [sass/embedded-host-node#269]
I fear this is not really the intended use of this package, but as at present it's the only way we can manage an installation of dart-sass on a production server (allowing for package.json versioning), I wondered if it was possible to make the dart-sass build that is pulled in for the relevant os/architecture a global install, so it can then be run without needing to know its intalled location?

At present even after installing this package, we have to hardcode a path within node_modules to the relevant architecture dart-sass has been installed in to call on it, is it possible to make this binary be installed automatically somewhere on the PATH ?

**Comment by nex3** [comment]
If you're only using the executable, it may be easier for you to use the standalone release or install it through Homebrew. For the npm releases, there's not really a better way for us to handle installs than what npm provides out of the box.

**Comment by atiro** [comment]
We can't use homebrew on production servers and we can't easily manage updates if we are just manually installing a release. Until dart-sass gets packaged into Ubuntu the only way we can use it on production is via this package, but because it doesn't install the dart-sass executable globally we then have to work out what path (based on the architecture) it's been installed under. Was a hope that might be possible via a global install of the executable in this package, but I realise that's not what it was intended for. 

Many thanks for responding and for the project.
