### ISSUE TITLE
1.70 picking up wrong architecture on Azure Ubuntu servers

### ISSUE THREAD

**Issue by atiro** [sass/embedded-host-node#271]
Upgrading the package to 1.70 is breaking for us running on a Azure Ubuntu server, it's switched to thinking we need musl-x64 architecture instead of x64. Downgrading to 1.69.5 and it works again. 

Linux 5.15.0-1053-azure #61~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

**Comment by ntkme** [comment]
> Upgrading the package to 1.70 is breaking for us running on a Azure Ubuntu server, it's switched to thinking we need musl-x64 architecture instead of x64.

It is expected to install both linux-x64 and linux-musl-x64 at the same time.

---

What is the exact command and the error message you're getting?

What's your node version, npm or yarn version, and how did you install?

**Comment by atiro** [comment]
Sorry for slow reply, we were on an older node version, have just tried going through a few different versions and from node 18 it starts installing both but before that just the musl-x64 version. Thanks for reply, will close the ticket
