### ISSUE TITLE
Allow configuring path to dart-sass executable

### ISSUE THREAD

**Issue by Demivan** [sass/embedded-host-node#273]
It is not possible to run dynamically linked libraries on NixOS. But there is `dart-sass package` available for it.

Please, allow configuring path to dart-sass executable or add an option to use globally installed executable.

I have tested and returning `['dart-sass']` from `compilerCommand` works fine.

**Comment by ntkme** [comment]
> It is not possible to run dynamically linked libraries on NixOS.

Not necessarily. The Ruby version of sass-embedded has a solution: https://ntk.me/2023/06/04/invoking-ld-linux-so/
It’s complicated and only benefits a tiny user group.

Usually, NixOS users do their own patching. In this case you can just replace the compiler-path.js all together. However, be very careful with the version. The dart-sass and sass-embedded are released in matching versions. You should always use matching versions. If you use a mismatched version, there is a chance that the protocol becomes incompatible.

**Comment by Demivan** [comment]
I meant that it is not possible to run executables bundled with this npm package.

But you are correct, I can just patch compiler-path.js myself. Just thought that it could be a nice feature to be able to use a custom binary. But if protocol is changing often, that would not be a good idea.

Closing this
