### ISSUE TITLE
Export SassBoolean is missing.

### ISSUE THREAD

**Issue by rvock** [sass/embedded-host-node#337]
The export for SassBoolean is undefined.

The `index.mjs` defines the export:
https://github.com/sass/embedded-host-node/blob/248437e15c67a352a9971c8cb3e9addbd8afc107/lib/index.mjs#L19

But it is not part of the export of `index.ts`:
https://github.com/sass/embedded-host-node/blob/248437e15c67a352a9971c8cb3e9addbd8afc107/lib/index.ts

This breaks usage of `sass-embedded` as drop-in replacement, if my code is using SassBoolean.

**Comment by guillaumerochelle** [comment]
Hello,
I'm trying to migrate a script from `sass` to `sass-embedded` and can't use `SassBoolean` anymore.

The script tries to identify the type with:
```typescript
if (value instanceof SassBoolean) {
  (...)
}
```

At runtime, the following error is thrown:
`Error: TypeError: Right-hand side of 'instanceof' is not an object`

I realized `SassBoolean` is an interface and not a class:
https://github.com/sass/embedded-host-node/blob/248437e15c67a352a9971c8cb3e9addbd8afc107/lib/src/value/boolean.ts#L15

Therefore, it is not present here in the compiled `index.js` along sassFalse and sassTrue:
```javascript
var boolean_2 = require("./src/value/boolean");
Object.defineProperty(exports, "sassFalse", { enumerable: true, get: function () { return boolean_2.sassFalse; } });
Object.defineProperty(exports, "sassTrue", { enumerable: true, get: function () { return boolean_2.sassTrue; } });
```

Should one use `sassFalse` and `sassTrue` instead ?
As is, `SassBoolean` still breaks usage of `sass-embedded` as drop-in replacement, as mentioned by @rvock.
