### ISSUE TITLE
Using legacy APIs with importers triggers `@import` deprecation warning

### ISSUE THREAD

**Issue by sapphi-red** [sass/embedded-host-node#340]
Even if the code doesn't contain `@import`, [the `@import` deprecation warning](https://sass-lang.com/documentation/breaking-changes/import/) appears.

```
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
5 │ ;@import "sass-embedded-legacy-load-done:0";
  │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
```

While I can set `silenceDeprecations`, it's a bit confusing.

Reproduction:
1. clone https://github.com/sapphi-red-repros/sass-embedded-legacy-importer-triggers-import-deprecated-warning
2. run `npm i`
3. run `node index.js`

**Comment by ntkme** [comment]
This is somewhat expected, due to the way the legacy API in the embedded-host-node is emulated with modern API.

#309 might fix this but we’ve decided that it’s not worth to do such a major rewrite given that the legacy API will be removed soon in 2.0.0.

**Comment by sapphi-red** [comment]
Is it possible to filter out the deprecation warning containing `sass-embedded-legacy-load-done` by default? I think that would suffice for my case.

**Comment by ntkme** [comment]
> Is it possible to filter out the deprecation warning containing `sass-embedded-legacy-load-done` by default?

It's possible. However, filtering out the warning internally is only a partial workaround for the default config. When a user choose to opt-in with `fatalDeprecations: ['import']`, it will crash the compilation.

**Comment by ntkme** [comment]
That is certainly possible, but unfortunately not as straightforward as you would think. 

The main problem is that the event dispatcher in a synchronous compiler currently dispatches log event asynchronously, meaning anything thrown in logger will just become unhandled exception that is not catchable. See original discussion here: https://github.com/sass/embedded-host-node/pull/261#issuecomment-1870717773

**Comment by sapphi-red** [comment]
Ah, I see.
