### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Splaktar** [sass/embedded-host-node#47]
Is there any documentation for this?

I was confused by the repo name and posted a similar question in https://github.com/sass/dart-sass-embedded/issues/39 which was closed and I was sent here.

Is there any guidance for using this with an Angular project?

Thank you

**Comment by nex3** [comment]
We're still working on getting this package up and running, so our focus for now is on reaching basic functionality. Once it's in a place where it's fit to be used more broadly, we'll definitely document how to do so.

Note that in general, this aims to provide the same API as the `sass` and `node-sass` packages, so you can try using it as a drop-in replacement for those, although be aware that it's still missing a substantial chunk of functionality.

**Comment by Splaktar** [comment]
OK, thank you for the info. Jeremy has been asking me to try it with Angular Material's website which uses the Angular CLI, but it's not clear that this is viable or possible atm. I'll get in touch with the Angular CLI team to see if they have any plans for supporting this, but I'm guessing that they won't be able to do so until there are some docs.

**Comment by nex3** [comment]
I believe Angular uses Webpack to drive its imports, so this won't be (easily) usable from there until it at least supports importer plugins.

**Comment by Splaktar** [comment]
Yeah, it looks like the Angular CLI team tried things out a bit this week.

Missing features they need
- result stats need to return `includedFiles`
- `importer`, `includePaths` and `outputStyle` options

**Comment by nex3** [comment]
> * result stats need to return `includedFiles`

Can you elaborate on what this is needed for?

**Comment by Splaktar** [comment]
@alan-agius4 thank you for looking into `sass-embedded` with the Angular CLI. Can you please provide some of the context requested above?

**Comment by nex3** [comment]
We have a full README now and the embedded host is also documented on the Sass website, so I'm going to close this out.
